<a href="https://colab.research.google.com/github/anubhavgupta1/D2L.AI/blob/main/Preliminaries/Data%20Manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Preliminaries

In [1]:
!pip install -U mxnet-cu101==1.7.0

     |███████████████████████████████▌| 834.1MB 1.3MB/s eta 0:00:09tcmalloc: large alloc 1147494400 bytes == 0x6578a000 @  0x7fbbb0254615 0x591e47 0x4cc179 0x4cc2db 0x50a1cc 0x50beb4 0x507be4 0x509900 0x50a2fd 0x50beb4 0x507be4 0x509900 0x50a2fd 0x50cc96 0x58e683 0x50c127 0x58e683 0x50c127 0x58e683 0x50c127 0x58e683 0x50c127 0x5095c8 0x50a2fd 0x50beb4 0x507be4 0x509900 0x50a2fd 0x50beb4 0x5095c8 0x50a2fd
     |████████████████████████████████| 846.0MB 21kB/s 
  Found existing installation: graphviz 0.10.1
    Uninstalling graphviz-0.10.1:
      Successfully uninstalled graphviz-0.10.1


## Data Manipulation

In [2]:
from mxnet import np, npx
npx.set_np()
import torch
import tensorflow as tf

### Vectors

In [3]:
x,y,z = np.arange(12),torch.arange(12), tf.range(12)
print("\nMxnet vector is : \n",x)
print("\nTorch vector is : \n",y)
print("\nTensorfow vector is : \n",z)


Mxnet vector is : 
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]

Torch vector is : 
 tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Tensorfow vector is : 
 tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11], shape=(12,), dtype=int32)


In [4]:
print("\nShape of Mxnet vector is : ", x.shape)
print("\nShape of torch vector is : ", y.shape)
print("\nShape of Tensorflow vector is : ", z.shape)


Shape of Mxnet vector is :  (12,)

Shape of torch vector is :  torch.Size([12])

Shape of Tensorflow vector is :  (12,)


### Reshape

In [5]:
x = x.reshape(3, 4)
y = y.reshape(3, 4)
z = tf.reshape(z,(3,4))
print("\nShape of mxnet is : ", x.shape)
print("\nShape of torch is : ", y.shape)
print("\nShape of tensorflow is : ", z.shape)


Shape of mxnet is :  (3, 4)

Shape of torch is :  torch.Size([3, 4])

Shape of tensorflow is :  (3, 4)


In [6]:
x = x.reshape(-1, 3)
y = y.reshape(-1, 3)
z = tf.reshape(z, (-1, 3))
print("\nShape of mxnet is : ", x.shape)
print("\nShape of torch is : ", y.shape)
print("\nShape of tensorflow is : ", z.shape)


Shape of mxnet is :  (4, 3)

Shape of torch is :  torch.Size([4, 3])

Shape of tensorflow is :  (4, 3)


### Zeros and ones matrices 

In [7]:
x = np.zeros((2,3,4))
y = torch.zeros((2,3,4))
z = tf.zeros((2,3,4))
print("\nmxnet is : \n\n", x)
print("\ntorch is : \n\n", y)
print("\ntensorflow is : \n\n", z)


mxnet is : 

 [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]

torch is : 

 tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

tensorflow is : 

 tf.Tensor(
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]], shape=(2, 3, 4), dtype=float32)


In [8]:
x = np.ones((2,3,4))
y = torch.ones((2,3,4))
z = tf.ones((2,3,4))
print("\nmxnet is : \n\n", x)
print("\ntorch is : \n\n", y)
print("\ntensorflow is : \n\n", z)


mxnet is : 

 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]

torch is : 

 tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

tensorflow is : 

 tf.Tensor(
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]], shape=(2, 3, 4), dtype=float32)


### Matrices with standard Gaussian (normal) distribution with a mean of 0 and standard deviation of 1

In [9]:
x = np.random.normal(0, 1, size=(3, 4))
y =torch.randn(3, 4)
z = tf.random.normal(shape=[3, 4])
print("\nmxnet is : \n\n", x)
print("\ntorch is : \n\n", y)
print("\ntensorflow is : \n\n", z)


mxnet is : 

 [[ 2.2122064   1.1630787   0.7740038   0.4838046 ]
 [ 1.0434403   0.29956347  1.1839255   0.15302546]
 [ 1.8917114  -1.1688148  -1.2347414   1.5580711 ]]

torch is : 

 tensor([[-0.7810, -0.7704,  1.1751,  0.3655],
        [-0.9364,  0.0767,  0.2606, -0.8849],
        [-0.6849, -1.9081,  0.1182,  1.2463]])

tensorflow is : 

 tf.Tensor(
[[ 0.2488511  -0.41741255  1.0644808  -0.34942544]
 [-1.1500967   0.4712437   0.3369736   1.209013  ]
 [-0.5445245  -0.44578797  1.424835    0.02279674]], shape=(3, 4), dtype=float32)


### Constants

In [10]:
x = np.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
y = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
z = tf.constant([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print("\nmxnet is : \n\n", x)
print("\ntorch is : \n\n", y)
print("\ntensorflow is : \n\n", z)


mxnet is : 

 [[2. 1. 4. 3.]
 [1. 2. 3. 4.]
 [4. 3. 2. 1.]]

torch is : 

 tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

tensorflow is : 

 tf.Tensor(
[[2 1 4 3]
 [1 2 3 4]
 [4 3 2 1]], shape=(3, 4), dtype=int32)


### Operations

In [11]:
print("Mxnet Operations")
x = np.array([1, 2, 4, 8])
y = np.array([2, 2, 2, 2])
print("\nADD",x + y)
print("\nSUBTRACTION : ",x - y)
print("\nMULTIPLY : ",x * y)
print("\nDIVISION : ",x / y)
print("\nPOWER : ",x ** y)
print("\nExponential : ",np.exp(x))

Mxnet Operations

ADD [ 3.  4.  6. 10.]

SUBTRACTION :  [-1.  0.  2.  6.]

MULTIPLY :  [ 2.  4.  8. 16.]

DIVISION :  [0.5 1.  2.  4. ]

POWER :  [ 1.  4. 16. 64.]

Exponential :  [2.7182817e+00 7.3890562e+00 5.4598148e+01 2.9809580e+03]


In [12]:
print("Torch Operations")
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
print("\nADD",x + y)
print("\nSUBTRACTION : ",x - y)
print("\nMULTIPLY : ",x * y)
print("\nDIVISION : ",x / y)
print("\nPOWER : ",x ** y)
print("\nExponential : ", torch.exp(x))

Torch Operations

ADD tensor([ 3.,  4.,  6., 10.])

SUBTRACTION :  tensor([-1.,  0.,  2.,  6.])

MULTIPLY :  tensor([ 2.,  4.,  8., 16.])

DIVISION :  tensor([0.5000, 1.0000, 2.0000, 4.0000])

POWER :  tensor([ 1.,  4., 16., 64.])

Exponential :  tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])


In [13]:
print("Tensorflow Operations")
x = tf.constant([1.0, 2, 4, 8])
y = tf.constant([2.0, 2, 2, 2])
print("\nADD",x + y)
print("\nSUBTRACTION : ",x - y)
print("\nMULTIPLY : ",x * y)
print("\nDIVISION : ",x / y)
print("\nPOWER : ",x ** y)
print("\nExponential : ", tf.exp(x))

Tensorflow Operations

ADD tf.Tensor([ 3.  4.  6. 10.], shape=(4,), dtype=float32)

SUBTRACTION :  tf.Tensor([-1.  0.  2.  6.], shape=(4,), dtype=float32)

MULTIPLY :  tf.Tensor([ 2.  4.  8. 16.], shape=(4,), dtype=float32)

DIVISION :  tf.Tensor([0.5 1.  2.  4. ], shape=(4,), dtype=float32)

POWER :  tf.Tensor([ 1.  4. 16. 64.], shape=(4,), dtype=float32)

Exponential :  tf.Tensor([2.7182817e+00 7.3890562e+00 5.4598148e+01 2.9809580e+03], shape=(4,), dtype=float32)


### Concatenation

In [14]:
print("Concatenation in mxnet : ")
X = np.arange(12).reshape(3, 4)
Y = np.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print("\n\nX : \n", X,"\n\nY : \n", Y,
      "\n\nConcatenation along rows : \n",np.concatenate([X, Y], axis=0), 
      "\n\nConcatenation along columns : \n",np.concatenate([X, Y], axis=1))

Concatenation in mxnet : 


X : 
 [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]] 

Y : 
 [[2. 1. 4. 3.]
 [1. 2. 3. 4.]
 [4. 3. 2. 1.]] 

Concatenation along rows : 
 [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [ 2.  1.  4.  3.]
 [ 1.  2.  3.  4.]
 [ 4.  3.  2.  1.]] 

Concatenation along columns : 
 [[ 0.  1.  2.  3.  2.  1.  4.  3.]
 [ 4.  5.  6.  7.  1.  2.  3.  4.]
 [ 8.  9. 10. 11.  4.  3.  2.  1.]]


In [15]:
print("Sum of matrix X : ", X.sum())

Sum of matrix X :  66.0


In [16]:
print("Concatenation in torch : ")
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print("\n\nX : \n", X,"\n\nY : \n", Y,
      "\n\nConcatenation along rows : \n",torch.cat((X, Y), dim=0), 
      "\n\nConcatenation along columns : \n",torch.cat((X, Y), dim=1))

Concatenation in torch : 


X : 
 tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]) 

Y : 
 tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]]) 

Concatenation along rows : 
 tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]]) 

Concatenation along columns : 
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])


In [17]:
print("Sum of matrix X : ", X.sum())

Sum of matrix X :  tensor(66.)


In [18]:
print("Concatenation in TensorFlow : ")
X = tf.reshape(tf.range(12, dtype=tf.float32), (3, 4))
Y = tf.constant([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print("\n\nX : \n", X,"\n\nY : \n", Y,
      "\n\nConcatenation along rows : \n",tf.concat([X, Y], axis=0), 
      "\n\nConcatenation along columns : \n",tf.concat([X, Y], axis=1))

Concatenation in TensorFlow : 


X : 
 tf.Tensor(
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]], shape=(3, 4), dtype=float32) 

Y : 
 tf.Tensor(
[[2. 1. 4. 3.]
 [1. 2. 3. 4.]
 [4. 3. 2. 1.]], shape=(3, 4), dtype=float32) 

Concatenation along rows : 
 tf.Tensor(
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [ 2.  1.  4.  3.]
 [ 1.  2.  3.  4.]
 [ 4.  3.  2.  1.]], shape=(6, 4), dtype=float32) 

Concatenation along columns : 
 tf.Tensor(
[[ 0.  1.  2.  3.  2.  1.  4.  3.]
 [ 4.  5.  6.  7.  1.  2.  3.  4.]
 [ 8.  9. 10. 11.  4.  3.  2.  1.]], shape=(3, 8), dtype=float32)


In [19]:
print("Sum of matrix X : ", tf.reduce_sum(X))

Sum of matrix X :  tf.Tensor(66.0, shape=(), dtype=float32)


### Broadcasting Mechanism

In [20]:
a, b = np.arange(3).reshape(3, 1), np.arange(2).reshape(1, 2)
print("Broadcasting in Mxnet : ")
print("\n\na : \n",a)
print("\n\nb : \n",b)
print("\n\na+b : \n",a+b)

Broadcasting in Mxnet : 


a : 
 [[0.]
 [1.]
 [2.]]


b : 
 [[0. 1.]]


a+b : 
 [[0. 1.]
 [1. 2.]
 [2. 3.]]


In [21]:
a,b = torch.arange(3).reshape((3, 1)), torch.arange(2).reshape((1, 2))
print("Broadcasting in torch : ")
print("\n\na : \n",a)
print("\n\nb : \n",b)
print("\n\na+b : \n",a+b)

Broadcasting in torch : 


a : 
 tensor([[0],
        [1],
        [2]])


b : 
 tensor([[0, 1]])


a+b : 
 tensor([[0, 1],
        [1, 2],
        [2, 3]])


In [22]:
a, b = tf.reshape(tf.range(3), (3, 1)), tf.reshape(tf.range(2), (1, 2))
print("Broadcasting in tensorflow : ")
print("\n\na : \n",a)
print("\n\nb : \n",b)
print("\n\na+b : \n",a+b)

Broadcasting in tensorflow : 


a : 
 tf.Tensor(
[[0]
 [1]
 [2]], shape=(3, 1), dtype=int32)


b : 
 tf.Tensor([[0 1]], shape=(1, 2), dtype=int32)


a+b : 
 tf.Tensor(
[[0 1]
 [1 2]
 [2 3]], shape=(3, 2), dtype=int32)


### Indexing and Slicing

In [23]:
X = np.arange(12).reshape(3, 4)
print("Indexing and slicing in mxnet : X(3,4)\n",X,
      "\n\nLast Row of X is : X[-1]\n",X[-1],
      "\n\nLast Column of X is : X[:,-1]\n",X[:,-1],
      "\n\nSecond and third row of X is : X[1:3]\n", X[1:3],
      "\n\n Value at [1, 2] is : ",X[1,2],
      "\n\nFirst two rows but all columns : X[0:2, :]\n",X[0:2, :])
X[1, 2] = 9
print("\n\nModified X is X[1, 2] = 9 \n", X)
X[0:2, :] = 12
print("\n\nModified X is X[0:2, :] = 12 \n", X)

Indexing and slicing in mxnet : X(3,4)
 [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]] 

Last Row of X is : X[-1]
 [ 8.  9. 10. 11.] 

Last Column of X is : X[:,-1]
 [ 3.  7. 11.] 

Second and third row of X is : X[1:3]
 [[ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]] 

 Value at [1, 2] is :  6.0 

First two rows but all columns : X[0:2, :]
 [[0. 1. 2. 3.]
 [4. 5. 6. 7.]]


Modified X is X[1, 2] = 9 
 [[ 0.  1.  2.  3.]
 [ 4.  5.  9.  7.]
 [ 8.  9. 10. 11.]]


Modified X is X[0:2, :] = 12 
 [[12. 12. 12. 12.]
 [12. 12. 12. 12.]
 [ 8.  9. 10. 11.]]


In [24]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
print("Indexing and slicing in Torch : X(3,4)\n",X,
      "\n\nLast Row of X is : X[-1]\n",X[-1],
      "\n\nLast Column of X is : X[:,-1]\n",X[:,-1],
      "\n\nSecond and third row of X is : X[1:3]\n", X[1:3],
      "\n\n Value at [1, 2] is : ",X[1,2],
      "\n\nFirst two rows but all columns : X[0:2, :]\n",X[0:2, :])
X[1, 2] = 9
print("\n\nModified X is X[1, 2] = 9 \n", X)
X[0:2, :] = 12
print("\n\nModified X is X[0:2, :] = 12 \n", X)

Indexing and slicing in Torch : X(3,4)
 tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]) 

Last Row of X is : X[-1]
 tensor([ 8.,  9., 10., 11.]) 

Last Column of X is : X[:,-1]
 tensor([ 3.,  7., 11.]) 

Second and third row of X is : X[1:3]
 tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]) 

 Value at [1, 2] is :  tensor(6.) 

First two rows but all columns : X[0:2, :]
 tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])


Modified X is X[1, 2] = 9 
 tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])


Modified X is X[0:2, :] = 12 
 tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])


In [25]:
X = tf.reshape(tf.range(12, dtype=tf.float32), (3, 4))
print("Indexing and slicing in Torch : X(3,4)\n",X,
      "\n\nLast Row of X is : X[-1]\n",X[-1],
      "\n\nLast Column of X is : X[:,-1]\n",X[:,-1],
      "\n\nSecond and third row of X is : X[1:3]\n", X[1:3],
      "\n\n Value at [1, 2] is : ",X[1,2],
      "\n\nFirst two rows but all columns : X[0:2, :]\n",X[0:2, :])
X_ = tf.Variable(X)
X_[1, 2].assign(9)
print("\n\nModified X is X_[1, 2].assign(9) \n", X_)
X_ = tf.Variable(X)
X_[0:2, :].assign(tf.ones(X_[0:2,:].shape, dtype = tf.float32) * 12)
print("\n\nModified X is X_[0:2, :].assign(tf.ones(X_[0:2,:].shape, dtype = tf.float32) * 12) \n", X_)

Indexing and slicing in Torch : X(3,4)
 tf.Tensor(
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]], shape=(3, 4), dtype=float32) 

Last Row of X is : X[-1]
 tf.Tensor([ 8.  9. 10. 11.], shape=(4,), dtype=float32) 

Last Column of X is : X[:,-1]
 tf.Tensor([ 3.  7. 11.], shape=(3,), dtype=float32) 

Second and third row of X is : X[1:3]
 tf.Tensor(
[[ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]], shape=(2, 4), dtype=float32) 

 Value at [1, 2] is :  tf.Tensor(6.0, shape=(), dtype=float32) 

First two rows but all columns : X[0:2, :]
 tf.Tensor(
[[0. 1. 2. 3.]
 [4. 5. 6. 7.]], shape=(2, 4), dtype=float32)


Modified X is X_[1, 2].assign(9) 
 <tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  9.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>


Modified X is X_[0:2, :].assign(tf.ones(X_[0:2,:].shape, dtype = tf.float32) * 12) 
 <tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[12., 12., 12., 12.],
       [1

### Conversion to Other Python Objects

In [26]:
X = np.arange(12).reshape(3, 4)
A = X.asnumpy()
B = np.array(A)
a = np.array([3.5])
print("Conversion In mxnet : ")
print(type(A), type(B),a, a.item(), float(a), int(a))

Conversion In mxnet : 
<class 'numpy.ndarray'> <class 'mxnet.numpy.ndarray'> [3.5] 3.5 3.5 3


In [27]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
A = X.numpy()
B = torch.tensor(A)
a = torch.tensor([3.5])
print("Conversion In torch : ")
print(type(A), type(B),a, a.item(), float(a), int(a))

Conversion In torch : 
<class 'numpy.ndarray'> <class 'torch.Tensor'> tensor([3.5000]) 3.5 3.5 3


In [28]:
X = tf.reshape(tf.range(12, dtype=tf.float32), (3, 4))
A = X.numpy()
B = tf.constant(A)
a = tf.constant([3.5]).numpy()
print("Conversion In tensorflow : ")
print(type(A), type(B),a, a.item(), float(a), int(a))

Conversion In tensorflow : 
<class 'numpy.ndarray'> <class 'tensorflow.python.framework.ops.EagerTensor'> [3.5] 3.5 3.5 3
