<a href="https://colab.research.google.com/github/anubhavgupta1/D2L.AI/blob/main/Preliminaries/Linear%20Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Preliminaries

In [1]:
!pip install -U mxnet-cu101==1.7.0

     |███████████████████████████████▌| 834.1MB 1.3MB/s eta 0:00:10tcmalloc: large alloc 1147494400 bytes == 0x65ba2000 @  0x7f768aec8615 0x591e47 0x4cc179 0x4cc2db 0x50a1cc 0x50beb4 0x507be4 0x509900 0x50a2fd 0x50beb4 0x507be4 0x509900 0x50a2fd 0x50cc96 0x58e683 0x50c127 0x58e683 0x50c127 0x58e683 0x50c127 0x58e683 0x50c127 0x5095c8 0x50a2fd 0x50beb4 0x507be4 0x509900 0x50a2fd 0x50beb4 0x5095c8 0x50a2fd
     |████████████████████████████████| 846.0MB 21kB/s 
  Found existing installation: graphviz 0.10.1
    Uninstalling graphviz-0.10.1:
      Successfully uninstalled graphviz-0.10.1


## Linear Algebra

In [2]:
from mxnet import np, npx
npx.set_np()
import torch
import tensorflow as tf

### Scalors

In [3]:
x = np.array(3.0)
y = np.array(2.0)
print("Scalors in Mxnet : ")
print("\nx = ", x,", y = ",y,
      "\nx + y  = ", x + y,
      "\nx * y  = ", x * y,
      "\nx / y  = " ,x / y,
      "\nx ** y = ", x ** y)

Scalors in Mxnet : 

x =  3.0 , y =  2.0 
x + y  =  5.0 
x * y  =  6.0 
x / y  =  1.5 
x ** y =  9.0


In [4]:
x = torch.tensor([3.0])
y = torch.tensor([2.0])
print("Scalors in Torch : ")
print("\nx = ", x,", y = ",y,
      "\nx + y  = ", x + y,
      "\nx * y  = ", x * y,
      "\nx / y  = " ,x / y,
      "\nx ** y = ", x ** y)

Scalors in Torch : 

x =  tensor([3.]) , y =  tensor([2.]) 
x + y  =  tensor([5.]) 
x * y  =  tensor([6.]) 
x / y  =  tensor([1.5000]) 
x ** y =  tensor([9.])


In [5]:
x = tf.constant([3.0])
y = tf.constant([2.0])
print("Scalors in Tensorflow : ")
print("\nx = ", x,", y = ",y,
      "\nx + y  = ", x + y,
      "\nx * y  = ", x * y,
      "\nx / y  = " ,x / y,
      "\nx ** y = ", x ** y)

Scalors in Tensorflow : 

x =  tf.Tensor([3.], shape=(1,), dtype=float32) , y =  tf.Tensor([2.], shape=(1,), dtype=float32) 
x + y  =  tf.Tensor([5.], shape=(1,), dtype=float32) 
x * y  =  tf.Tensor([6.], shape=(1,), dtype=float32) 
x / y  =  tf.Tensor([1.5], shape=(1,), dtype=float32) 
x ** y =  tf.Tensor([9.], shape=(1,), dtype=float32)


### Vectors

In [6]:
x,y,z = np.arange(12),torch.arange(12), tf.range(12)
print("\nMxnet vector is : \n",x)
print("\nTorch vector is : \n",y)
print("\nTensorfow vector is : \n",z)


Mxnet vector is : 
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]

Torch vector is : 
 tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Tensorfow vector is : 
 tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11], shape=(12,), dtype=int32)


In [7]:
print("\nShape of Mxnet vector is : ", x.shape)
print("\nShape of torch vector is : ", y.shape)
print("\nShape of Tensorflow vector is : ", z.shape)


Shape of Mxnet vector is :  (12,)

Shape of torch vector is :  torch.Size([12])

Shape of Tensorflow vector is :  (12,)


### Matrices

In [8]:
x = x.reshape(3, 4)
y = y.reshape(3, 4)
z = tf.reshape(z,(3,4))
print("\nShape of mxnet is : ", x.shape)
print("\nShape of torch is : ", y.shape)
print("\nShape of tensorflow is : ", z.shape)


Shape of mxnet is :  (3, 4)

Shape of torch is :  torch.Size([3, 4])

Shape of tensorflow is :  (3, 4)


In [9]:
print("\nTranspose of mxnet is : ", x.T.shape)
print("\nTranspose of torch is : ", y.T.shape)
print("\nTranspose of tensorflow is : ", tf.transpose(z).shape)


Transpose of mxnet is :  (4, 3)

Transpose of torch is :  torch.Size([4, 3])

Transpose of tensorflow is :  (4, 3)


### Tensors

In [10]:
X, Y, Z = np.arange(24).reshape(2, 3, 4),  torch.arange(24).reshape(2, 3, 4), tf.reshape(tf.range(24), (2, 3, 4))
print("\Mxnet vector is : \n\n",X)
print("\nTorch vector is : \n\n",Y)
print("\nTensorfow vector is : \n\n",Z)

\Mxnet vector is : 

 [[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]

 [[12. 13. 14. 15.]
  [16. 17. 18. 19.]
  [20. 21. 22. 23.]]]

Torch vector is : 

 tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

Tensorfow vector is : 

 tf.Tensor(
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]], shape=(2, 3, 4), dtype=int32)


### Matrix Addition

In [11]:
A = np.arange(20).reshape(5, 4)
# Assign a copy of `A` to `B` by allocating new memory
B = A.copy()  
print("Matrix Addition in Mxnet is : ")
print("\n\nA : \n",A,"\n\nA + B : \n", A + B)

Matrix Addition in Mxnet is : 


A : 
 [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]
 [16. 17. 18. 19.]] 

A + B : 
 [[ 0.  2.  4.  6.]
 [ 8. 10. 12. 14.]
 [16. 18. 20. 22.]
 [24. 26. 28. 30.]
 [32. 34. 36. 38.]]


In [12]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
# Assign a copy of `A` to `B` by allocating new memory
B = A.clone()  
print("Matrix Addition in Torch is : ")
print("\n\nA : \n",A,"\n\nA + B : \n", A + B)

Matrix Addition in Torch is : 


A : 
 tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]]) 

A + B : 
 tensor([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]])


In [13]:
A = tf.reshape(tf.range(20, dtype=tf.float32), (5, 4))
# No cloning of `A` to `B` by allocating new memory
B = A  
print("Matrix Addition in Tenorflow is : ")
print("\n\nA : \n",A,"\n\nA + B : \n", A + B)

Matrix Addition in Tenorflow is : 


A : 
 tf.Tensor(
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]
 [16. 17. 18. 19.]], shape=(5, 4), dtype=float32) 

A + B : 
 tf.Tensor(
[[ 0.  2.  4.  6.]
 [ 8. 10. 12. 14.]
 [16. 18. 20. 22.]
 [24. 26. 28. 30.]
 [32. 34. 36. 38.]], shape=(5, 4), dtype=float32)


### Hadamard product : Element wise product

In [14]:
A = np.arange(20).reshape(5, 4)
# Assign a copy of `A` to `B` by allocating new memory
B = A.copy()  
print("Mxnet is : ")
print("\n\nA : \n",A,"\n\nA + B : \n", A * B)

Mxnet is : 


A : 
 [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]
 [16. 17. 18. 19.]] 

A + B : 
 [[  0.   1.   4.   9.]
 [ 16.  25.  36.  49.]
 [ 64.  81. 100. 121.]
 [144. 169. 196. 225.]
 [256. 289. 324. 361.]]


In [15]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
# Assign a copy of `A` to `B` by allocating new memory
B = A.clone()  
print("Torch is : ")
print("\n\nA : \n",A,"\n\nA + B : \n", A * B)

Torch is : 


A : 
 tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]]) 

A + B : 
 tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])


In [16]:
A = tf.reshape(tf.range(20, dtype=tf.float32), (5, 4))
# No cloning of `A` to `B` by allocating new memory
B = A 
print("Tensorflow is : ")
print("\n\nA : \n",A,"\n\nA + B : \n", A * B)

Tensorflow is : 


A : 
 tf.Tensor(
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]
 [16. 17. 18. 19.]], shape=(5, 4), dtype=float32) 

A + B : 
 tf.Tensor(
[[  0.   1.   4.   9.]
 [ 16.  25.  36.  49.]
 [ 64.  81. 100. 121.]
 [144. 169. 196. 225.]
 [256. 289. 324. 361.]], shape=(5, 4), dtype=float32)


### Scalor Matrix Operations

```
# This is formatted as code
```



In [17]:
a = 2
X = np.arange(12).reshape(3, 4)
print("Mxnet is : \n",X)
print("\n\nAddition is : \n",a + X, "\n\nMultiplication is : \n",(a * X))

Mxnet is : 
 [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


Addition is : 
 [[ 2.  3.  4.  5.]
 [ 6.  7.  8.  9.]
 [10. 11. 12. 13.]] 

Multiplication is : 
 [[ 0.  2.  4.  6.]
 [ 8. 10. 12. 14.]
 [16. 18. 20. 22.]]


In [18]:
a = 2
X = torch.arange(12).reshape(3, 4)
print("Torch is : \n",X)
print("\n\nAddition is : \n",a + X, "\n\nMultiplication is : \n",(a * X))

Torch is : 
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


Addition is : 
 tensor([[ 2,  3,  4,  5],
        [ 6,  7,  8,  9],
        [10, 11, 12, 13]]) 

Multiplication is : 
 tensor([[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22]])


In [19]:
a = 2
X = tf.reshape(tf.range(12), (3, 4))
print("Tensorflow is : \n",X)
print("\n\nAddition is : \n",a + X, "\n\nMultiplication is : \n",(a * X))

Tensorflow is : 
 tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]], shape=(3, 4), dtype=int32)


Addition is : 
 tf.Tensor(
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]], shape=(3, 4), dtype=int32) 

Multiplication is : 
 tf.Tensor(
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]], shape=(3, 4), dtype=int32)


### Reduction

In [20]:
x, y, z = np.arange(4), torch.arange(4, dtype=torch.float32), tf.range(4, dtype=tf.float32)
print("Mxnet is : ")
print(x)
print("Sum is : ",x.sum())
print("\nTorch is : ")
print(y)
print("Sum is : ",y.sum())
print("\nTensorfow is : ")
print(z)
print("Sum is : ",tf.reduce_sum(z))

Mxnet is : 
[0. 1. 2. 3.]
Sum is :  6.0

Torch is : 
tensor([0., 1., 2., 3.])
Sum is :  tensor(6.)

Tensorfow is : 
tf.Tensor([0. 1. 2. 3.], shape=(4,), dtype=float32)
Sum is :  tf.Tensor(6.0, shape=(), dtype=float32)


In [21]:
A = np.arange(12).reshape(3, 4)
print("Mxnet is : ")
print(A)
print("\nSum is : ",A.sum())
print("\nColumn wise Sum is : ",A.sum(axis=0))
print("\nColumn wise Sum is : ",A.sum(axis=0, keepdims=True))
print("\nRow wise Sum is : ",A.sum(axis=1))
print("\nRow wise Sum is : \n",A.sum(axis=1, keepdims=True))
print("\nMean of ",A.size," terms in A is : ",A.mean())
print("\nColumn wise mean is : ",A.mean(axis=0))
print("\nRow wise mean is : ",A.mean(axis=1))

Mxnet is : 
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]

Sum is :  66.0

Column wise Sum is :  [12. 15. 18. 21.]

Column wise Sum is :  [[12. 15. 18. 21.]]

Row wise Sum is :  [ 6. 22. 38.]

Row wise Sum is : 
 [[ 6.]
 [22.]
 [38.]]

Mean of  12  terms in A is :  5.5

Column wise mean is :  [4. 5. 6. 7.]

Row wise mean is :  [1.5 5.5 9.5]


In [22]:
B = torch.arange(12).reshape(3, 4).float()
print("Torch is : ")
print(B)
print("\nSum is : ",B.sum())
print("\nColumn wise Sum is : ",B.sum(axis=0))
print("\nColumn wise Sum is : ",B.sum(axis=0, keepdims=True))
print("\nRow wise Sum is : ",B.sum(axis=1))
print("\nRow wise Sum is : \n",B.sum(axis=1, keepdims=True))
print("\nMean of ",B.numel()," terms in B is : ",B.mean())
print("\nColumn wise mean is : ",B.mean(axis=0))
print("\nRow wise mean is : ",B.mean(axis=1))

Torch is : 
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

Sum is :  tensor(66.)

Column wise Sum is :  tensor([12., 15., 18., 21.])

Column wise Sum is :  tensor([[12., 15., 18., 21.]])

Row wise Sum is :  tensor([ 6., 22., 38.])

Row wise Sum is : 
 tensor([[ 6.],
        [22.],
        [38.]])

Mean of  12  terms in B is :  tensor(5.5000)

Column wise mean is :  tensor([4., 5., 6., 7.])

Row wise mean is :  tensor([1.5000, 5.5000, 9.5000])


In [23]:
C =  tf.reshape(tf.range(12), (3, 4))
print("Tensorfow is : ")
print(C) 
print("\nSum is : ",tf.reduce_sum(C))
print("\nColumn wise Sum is : ",tf.reduce_sum(C, axis=0))
print("\nColumn wise Sum is : ",tf.reduce_sum(C, axis=1, keepdims=True))
print("\nRow wise Sum is : ",tf.reduce_sum(C, axis=1))
print("\nRow wise Sum is : ",tf.reduce_sum(C, axis=1, keepdims=True))
print("\nMean of ",tf.size(C).numpy()," terms in C is : ",tf.reduce_mean(C))
print("\nColumn wise mean is : ",tf.reduce_mean(C, axis=0))
print("\nRow wise mean is : ",tf.reduce_mean(C, axis=1))

Tensorfow is : 
tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]], shape=(3, 4), dtype=int32)

Sum is :  tf.Tensor(66, shape=(), dtype=int32)

Column wise Sum is :  tf.Tensor([12 15 18 21], shape=(4,), dtype=int32)

Column wise Sum is :  tf.Tensor(
[[ 6]
 [22]
 [38]], shape=(3, 1), dtype=int32)

Row wise Sum is :  tf.Tensor([ 6 22 38], shape=(3,), dtype=int32)

Row wise Sum is :  tf.Tensor(
[[ 6]
 [22]
 [38]], shape=(3, 1), dtype=int32)

Mean of  12  terms in C is :  tf.Tensor(5, shape=(), dtype=int32)

Column wise mean is :  tf.Tensor([4 5 6 7], shape=(4,), dtype=int32)

Row wise mean is :  tf.Tensor([1 5 9], shape=(3,), dtype=int32)


### Dot Product

In [24]:
x, y = np.arange(4), np.ones(4)
print("Mxnet is : ","\nx : ",x,"\ny : ", y)
print("\nDot product is : ",np.dot(x, y),"\nDot product is : ", np.sum(x * y))

Mxnet is :  
x :  [0. 1. 2. 3.] 
y :  [1. 1. 1. 1.]

Dot product is :  6.0 
Dot product is :  6.0


In [25]:
x, y = torch.arange(4, dtype = torch.float32) , torch.ones(4, dtype = torch.float32)
print("Torch is : ","\nx : ",x,"\ny : ", y)
print("\nDot product is : ",torch.dot(x, y),"\nDot product is : ", torch.sum(x * y))

Torch is :  
x :  tensor([0., 1., 2., 3.]) 
y :  tensor([1., 1., 1., 1.])

Dot product is :  tensor(6.) 
Dot product is :  tensor(6.)


In [26]:
x, y = tf.range(4, dtype=tf.float32) , tf.ones(4, dtype=tf.float32)
print("Tensorflow is : ","\nx : ",x,"\ny : ", y)
print("\nDot product is : ",tf.tensordot(x, y, axes=1),"\nDot product is : ", tf.reduce_sum(x * y))

Tensorflow is :  
x :  tf.Tensor([0. 1. 2. 3.], shape=(4,), dtype=float32) 
y :  tf.Tensor([1. 1. 1. 1.], shape=(4,), dtype=float32)

Dot product is :  tf.Tensor(6.0, shape=(), dtype=float32) 
Dot product is :  tf.Tensor(6.0, shape=(), dtype=float32)


## Matrix-Vector Products

In [27]:
A, B = np.arange(6).reshape(3,2), np.ones(shape=(2, 3))
print("Mxnet is : ","\nA : \n",A,"\nB : \n", B)
print("\nDot product is : \n",np.dot(A, B))

Mxnet is :  
A : 
 [[0. 1.]
 [2. 3.]
 [4. 5.]] 
B : 
 [[1. 1. 1.]
 [1. 1. 1.]]

Dot product is : 
 [[1. 1. 1.]
 [5. 5. 5.]
 [9. 9. 9.]]


In [28]:
A, B = torch.arange(6, dtype = torch.float32).reshape(3,2), torch.ones(2, 3)
print("Torch is : ","\nA : \n",A,"\nB : \n", B)
print("\nDot product is : \n", torch.mm(A, B))

Torch is :  
A : 
 tensor([[0., 1.],
        [2., 3.],
        [4., 5.]]) 
B : 
 tensor([[1., 1., 1.],
        [1., 1., 1.]])

Dot product is : 
 tensor([[1., 1., 1.],
        [5., 5., 5.],
        [9., 9., 9.]])


In [29]:
A, B = tf.reshape(tf.range(12, dtype=tf.float32), (3, 4)) , tf.ones((4, 3), dtype=tf.float32)
print("Tensorflow is : ","\nA : \n",A,"\nB : \n", B)
print("\nDot product is : \n", tf.matmul(A, B))

Tensorflow is :  
A : 
 tf.Tensor(
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]], shape=(3, 4), dtype=float32) 
B : 
 tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(4, 3), dtype=float32)

Dot product is : 
 tf.Tensor(
[[ 6.  6.  6.]
 [22. 22. 22.]
 [38. 38. 38.]], shape=(3, 3), dtype=float32)


### Norms

In [30]:
a, b, c = np.array([3, -4]), torch.tensor([3.0, -4.0]), tf.constant([3.0, -4.0])
print("L1 Norm : ",np.linalg.norm(a),torch.norm(b),tf.norm(c))
print("L2 Norm : ",np.abs(a).sum(),torch.abs(b).sum(),tf.reduce_sum(tf.abs(c)))
a, b, c = np.array([3, -4,5]), torch.tensor([3.0, -4.0, 5.0]), tf.constant([3.0, -4.0, 5.0])
print("Frobenius norm : ", np.linalg.norm(a), torch.norm(b), tf.norm(c))

L1 Norm :  5.0 tensor(5.) tf.Tensor(5.0, shape=(), dtype=float32)
L2 Norm :  7.0 tensor(7.) tf.Tensor(7.0, shape=(), dtype=float32)
Frobenius norm :  7.071068 tensor(7.0711) tf.Tensor(7.071068, shape=(), dtype=float32)
