<a href="https://colab.research.google.com/github/anubhavgupta1/Dive-Into-Deep-Learning/blob/main/Deep%20Learning%20Computation/Parameters%20Management/tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  Deep Learning Computation

In [1]:
import tensorflow as tf

In [2]:
X = tf.random.uniform((2, 4))

### Model

In [3]:
net = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(4, activation=tf.nn.relu),
    tf.keras.layers.Dense(1),
])

In [4]:
print(net(X))

tf.Tensor(
[[0.06459555]
 [0.0595221 ]], shape=(2, 1), dtype=float32)


###  Parameter Access

In [5]:
print(net.layers[0].weights)

[]


In [6]:
print(net.layers[1].weights)

[<tf.Variable 'dense/kernel:0' shape=(4, 4) dtype=float32, numpy=
array([[-0.47655138, -0.7652339 ,  0.6957366 , -0.2765357 ],
       [-0.79900473, -0.32743424,  0.80454344,  0.673377  ],
       [ 0.613921  , -0.50493014,  0.27250236, -0.07820815],
       [-0.27871585, -0.48289123,  0.7165231 , -0.48762575]],
      dtype=float32)>, <tf.Variable 'dense/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>]


In [7]:
print(net.layers[2].weights)

[<tf.Variable 'dense_1/kernel:0' shape=(4, 1) dtype=float32, numpy=
array([[-0.31613576],
       [ 0.18145597],
       [ 0.04773796],
       [-0.02514958]], dtype=float32)>, <tf.Variable 'dense_1/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]


### Targeted Parameters

In [8]:
print(type(net.layers[2].weights[1]))

<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>


In [9]:
print(net.layers[1].weights[1])
print(tf.convert_to_tensor(net.layers[1].weights[1]))

<tf.Variable 'dense/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>
tf.Tensor([0. 0. 0. 0.], shape=(4,), dtype=float32)


In [10]:
print(net.layers[2].weights[1])
print(tf.convert_to_tensor(net.layers[2].weights[1]))

<tf.Variable 'dense_1/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>
tf.Tensor([0.], shape=(1,), dtype=float32)


### All Parameters at Once

In [11]:
print(net.layers[1].weights)

[<tf.Variable 'dense/kernel:0' shape=(4, 4) dtype=float32, numpy=
array([[-0.47655138, -0.7652339 ,  0.6957366 , -0.2765357 ],
       [-0.79900473, -0.32743424,  0.80454344,  0.673377  ],
       [ 0.613921  , -0.50493014,  0.27250236, -0.07820815],
       [-0.27871585, -0.48289123,  0.7165231 , -0.48762575]],
      dtype=float32)>, <tf.Variable 'dense/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>]


In [12]:
print(net.get_weights())

[array([[-0.47655138, -0.7652339 ,  0.6957366 , -0.2765357 ],
       [-0.79900473, -0.32743424,  0.80454344,  0.673377  ],
       [ 0.613921  , -0.50493014,  0.27250236, -0.07820815],
       [-0.27871585, -0.48289123,  0.7165231 , -0.48762575]],
      dtype=float32), array([0., 0., 0., 0.], dtype=float32), array([[-0.31613576],
       [ 0.18145597],
       [ 0.04773796],
       [-0.02514958]], dtype=float32), array([0.], dtype=float32)]


In [13]:
print(net.get_weights()[1])

[0. 0. 0. 0.]


### Parameter Initialization

In [14]:
net = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(
        4, activation=tf.nn.relu,
        kernel_initializer=tf.random_normal_initializer(mean=0, stddev=0.01),
        bias_initializer=tf.zeros_initializer()),
    tf.keras.layers.Dense(1)])

In [15]:
net(X)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.02344303],
       [-0.0155153 ]], dtype=float32)>

In [16]:
print(net.weights[0])

<tf.Variable 'dense_2/kernel:0' shape=(4, 4) dtype=float32, numpy=
array([[ 0.02132052,  0.00890239,  0.00287405,  0.00862987],
       [-0.00878582,  0.01448512,  0.01680341, -0.0047634 ],
       [ 0.00066721, -0.01237047,  0.00110255,  0.01364356],
       [ 0.00495838, -0.00505607,  0.01105706, -0.00502033]],
      dtype=float32)>


In [17]:
print(net.weights[1])

<tf.Variable 'dense_2/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>


In [18]:
net = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(
        4, activation=tf.nn.relu,
        kernel_initializer=tf.keras.initializers.Constant(1),
        bias_initializer=tf.zeros_initializer()),
    tf.keras.layers.Dense(1),
])


In [19]:
net(X)
print(net.weights[0])

<tf.Variable 'dense_4/kernel:0' shape=(4, 4) dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>


In [20]:
print(net.weights[1])

<tf.Variable 'dense_4/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>


In [21]:
net = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(
        4,
        activation=tf.nn.relu,
        kernel_initializer=tf.keras.initializers.GlorotUniform()),
    tf.keras.layers.Dense(
        1, kernel_initializer=tf.keras.initializers.Constant(1)),
])

In [22]:
net(X)
print(net.layers[1].weights[0])
print(net.layers[2].weights[0])

<tf.Variable 'dense_6/kernel:0' shape=(4, 4) dtype=float32, numpy=
array([[ 0.76686543,  0.18859547, -0.48563614,  0.7944835 ],
       [ 0.44747657,  0.03430814, -0.666409  ,  0.06782383],
       [ 0.6992405 , -0.2738868 ,  0.33867973, -0.1759783 ],
       [ 0.0094434 ,  0.6708191 , -0.2537601 ,  0.8048776 ]],
      dtype=float32)>
<tf.Variable 'dense_7/kernel:0' shape=(4, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.],
       [1.]], dtype=float32)>
