<a href="https://colab.research.google.com/github/anubhavgupta1/Dive-Into-Deep-Learning/blob/main/Linear%20Regression/Concise%20Implementation/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Regression

In [ ]:
!pip install d2l==0.16.1

In [2]:
from d2l import tensorflow as d2l
import numpy as np
import tensorflow as tf

### Generating the Dataset

In [3]:
true_w = tf.constant([2, -3.4])
true_b = 4.2
features, labels = d2l.synthetic_data(true_w, true_b, 1000)

### Reading the Dataset

In [4]:
def load_array(data_arrays, batch_size, is_train=True):  #@save
    """Construct a TensorFlow data iterator."""
    dataset = tf.data.Dataset.from_tensor_slices(data_arrays)
    if is_train:
        dataset = dataset.shuffle(buffer_size=1000)
    dataset = dataset.batch(batch_size)
    return dataset

In [5]:
batch_size = 10
data_iter = load_array((features, labels), batch_size)

In [6]:
next(iter(data_iter))

(<tf.Tensor: shape=(10, 2), dtype=float32, numpy=
 array([[-0.9033208 ,  2.2756672 ],
        [-0.7267111 , -0.43893915],
        [ 0.04427969,  0.3794744 ],
        [ 1.1815178 , -0.317781  ],
        [ 1.0038683 ,  1.4636891 ],
        [-0.03340807,  1.1346507 ],
        [-0.02190512,  0.6104773 ],
        [ 0.2776856 , -0.289722  ],
        [-0.89333826, -0.3612817 ],
        [ 0.5720077 , -0.59453505]], dtype=float32)>,
 <tf.Tensor: shape=(10, 1), dtype=float32, numpy=
 array([[-5.348733  ],
        [ 4.2340693 ],
        [ 2.9986713 ],
        [ 7.6414595 ],
        [ 1.2365103 ],
        [ 0.27719274],
        [ 2.077369  ],
        [ 5.739223  ],
        [ 3.623779  ],
        [ 7.365366  ]], dtype=float32)>)

### Defining the Model

In [7]:
# `keras` is the high-level API for TensorFlow
net = tf.keras.Sequential()
net.add(tf.keras.layers.Dense(1))

###Initializing Model Parameters

In [8]:
initializer = tf.initializers.RandomNormal(stddev=0.01)
net = tf.keras.Sequential()
net.add(tf.keras.layers.Dense(1, kernel_initializer=initializer))

### Defining the Loss Function

In [9]:
loss = tf.keras.losses.MeanSquaredError()

###Defining the Optimization Algorithm

In [10]:
trainer = tf.keras.optimizers.SGD(learning_rate=0.03)

### Training

In [11]:
num_epochs = 200
for epoch in range(num_epochs):
    for X, y in data_iter:
        with tf.GradientTape() as tape:
            l = loss(net(X, training=True), y)
        grads = tape.gradient(l, net.trainable_variables)
        trainer.apply_gradients(zip(grads, net.trainable_variables))
    l = loss(net(features), labels)
    if(epoch==0 or epoch%20==9):
      print(f'epoch {epoch + 1}, loss {l:f}')

epoch 1, loss 0.000213
epoch 10, loss 0.000095
epoch 30, loss 0.000094
epoch 50, loss 0.000094
epoch 70, loss 0.000094
epoch 90, loss 0.000096
epoch 110, loss 0.000095
epoch 130, loss 0.000094
epoch 150, loss 0.000094
epoch 170, loss 0.000094
epoch 190, loss 0.000095


In [12]:
w = net.get_weights()[0]
print('error in estimating w', true_w - tf.reshape(w, true_w.shape))
b = net.get_weights()[1]
print('error in estimating b', true_b - b)

error in estimating w tf.Tensor([-0.00028777  0.00116444], shape=(2,), dtype=float32)
error in estimating b [0.00039768]
